import { SafetyRule, FileCategory } from '@sweep/types';

export const xcodeDerivedData: SafetyRule = {
  id: 'xcode-derived-data',
  name: 'Xcode Derived Data',
  description: 'Build artifacts generated by Xcode for each project.',
  whySafeToRemove:
    'Derived Data is fully regenerated the next time you build a project in Xcode. Removing it does not affect your source code or app archives.',
  category: FileCategory.Cache,
  requiresConfirmation: true,
  paths: ['~/Library/Developer/Xcode/DerivedData/**'],
};

export const xcodeDeviceSupport: SafetyRule = {
  id: 'xcode-device-support',
  name: 'Xcode iOS Device Support',
  description: 'Debug symbols downloaded per connected iOS device and OS version.',
  whySafeToRemove:
    'These files are redownloaded automatically when you next connect a device running that iOS version. Old versions you no longer test on are safe to delete.',
  category: FileCategory.Cache,
  requiresConfirmation: true,
  paths: ['~/Library/Developer/Xcode/iOS DeviceSupport/**'],
};

export const xcodeSimulatorCaches: SafetyRule = {
  id: 'xcode-simulator-caches',
  name: 'Xcode Simulator Caches',
  description: 'Simulator runtime caches and temporary data.',
  whySafeToRemove: 'Simulator caches are regenerated on the next launch of an iOS simulator.',
  category: FileCategory.Cache,
  requiresConfirmation: true,
  paths: ['~/Library/Developer/CoreSimulator/Caches/**'],
};

export const xcodeRules: SafetyRule[] = [
  xcodeDerivedData,
  xcodeDeviceSupport,
  xcodeSimulatorCaches,
];
