import { SafetyRule, FileCategory } from '../types';

/**
 * Predefined Safety Rules for Sweep
 */
export const BUILTIN_SAFETY_RULES: SafetyRule[] = [
  {
    id: 'xcode-derived-data',
    name: 'Xcode DerivedData',
    description: 'Build artifacts and indexes generated by Xcode',
    whySafeToRemove: 'Xcode can safely regenerate these build artifacts when needed.',
    paths: ['~/Library/Developer/Xcode/DerivedData'],
    category: FileCategory.Cache,
    requiresConfirmation: true,
  },
  {
    id: 'npm-cache',
    name: 'npm Cache',
    description: 'Global npm package cache',
    whySafeToRemove: 'npm will re-download cached packages automatically on future installs.',
    paths: ['~/.npm/_cacache'],
    category: FileCategory.Cache,
    requiresConfirmation: true,
  },
];
